---
- name: Install nerdfonts
  block:
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "{{ var_file }}"
      with_first_found:
        - "{{ role_path }}/vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/vars/{{ ansible_distribution }}.yml"
        - "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
        - "{{ role_path }}/vars/{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: var_file

    - name: Install OS-specific dependencies
      ansible.builtin.include_tasks: "{{ var_file }}"
      with_first_found:
        - "{{ role_path }}/tasks/noauto_install_dep_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/noauto_install_dep_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/noauto_install_dep_{{ ansible_distribution }}.yml"
        - "{{ role_path }}/tasks/noauto_install_dep_{{ ansible_os_family }}.yml"
        - "{{ role_path }}/tasks/noauto_install_dep_{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: var_file

    - name: Install nerdfonts
      ansible.builtin.include_tasks:
        file: noauto_install_{{ nerdfonts_install_method }}.yml
