---
- name: Ensure nerdfonts are installed
  block:
    - name: Check if selected nerdfont (non-mono) is installed
      ansible.builtin.find:
        paths: "{{ nerdfonts_install_dir }}"
        patterns: "{{ nerdfonts_font }}*Regular.ttf"
      register: nerdfonts_regular
      become: true
      when: not nerdfonts_mono

    - name: Check if selected nerdfont (mono) is installed
      ansible.builtin.find:
        paths: "{{ nerdfonts_install_dir }}"
        patterns: "{{ nerdfonts_font }}*Mono-Regular.ttf"
      register: nerdfonts_regular
      become: true
      when: nerdfonts_mono

    - name: Install nerdfonts from source
      when: (nerdfonts_regular.files | default([]) | length) == 0
      block:
        - name: Ensure the installation folder exists
          ansible.builtin.file:
            path: "{{ nerdfonts_install_dir }}"
            state: directory
            mode: "0755"
            owner: root
            group: root
          become: true

        - name: Download specific font files
          ansible.builtin.get_url:
            url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v{{ nerdfonts_version }}/{{ nerdfonts_font }}.tar.xz"
            dest: "{{ nerdfonts_tmp_dir }}/{{ nerdfonts_font }}.tar.xz"
            mode: "0600"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"

        - name: Create folder for font files
          ansible.builtin.file:
            path: "{{ nerdfonts_tmp_dir }}/{{ nerdfonts_font }}"
            state: directory
            mode: "0755"
            owner: root
            group: root
          become: true

        - name: Extract font files
          ansible.builtin.unarchive:
            src: "{{ nerdfonts_tmp_dir }}/{{ nerdfonts_font }}.tar.xz"
            dest: "{{ nerdfonts_tmp_dir }}/{{ nerdfonts_font }}"
            remote_src: true
          become: true

        - name: Copy files to nerdfonts folder
          ansible.builtin.copy:
            src: "{{ nerdfonts_tmp_dir }}/{{ nerdfonts_font }}/"
            dest: "{{ nerdfonts_install_dir }}"
            owner: root
            group: root
            mode: "0755"
            remote_src: true
          become: true
          notify: "Update Font Cache"

        - name: "Remove Unwanted fonts"
          ansible.builtin.command: find {{ nerdfonts_install_dir }} -name '*indows*.ttf' -exec rm {} \+
          register: remove_windows_fonts
          changed_when: remove_windows_fonts.stdout | length > 0
          become: true

        - name: "Remove mono fonts"
          ansible.builtin.command: find {{ nerdfonts_install_dir }} -name '*Mono.ttf' -exec rm {} \+
          register: remove_mono_fonts
          changed_when: remove_mono_fonts.stdout | length > 0
          become: true
          become_user: "{{ ansible_user }}"
          when: not nerdfonts_mono

        - name: Remove temporary font files
          ansible.builtin.file:
            path: "{{ nerdfonts_tmp_dir }}/{{ nerdfonts_font }}"
            state: absent
          become: true

        - name: Remove font archive
          ansible.builtin.file:
            path: "{{ nerdfonts_tmp_dir }}/{{ nerdfonts_font }}.tar.xz"
            state: absent
